### PR TITLE
PUT API

### PR DESCRIPTION
**Pull request by Advaith2805**

### CODE REVIEW

**Comment by Samyukta-b** [comment]
can you give me the url for checking updateUSER

**Comment by Samyukta-b** [comment]
just send me all the details and i'll be taking a short break. i will review after i come back

**Comment by Advaith2805** [comment]
url: http://localhost:8080/updateUser
But its now not working in my postman(which I hadnt tested before very sorry) so you can deassign me there is some error

**Comment by Samyukta-b** [comment]
!deassign

**Pull request closed without merging**
