### PR TITLE
Created a POST API to add new user data to the database

### PR DESCRIPTION
**Pull request by Rojas-Binny**
image
This is the image containing the data of the new user added.

### CODE REVIEW

**Comment by Samyukta-b** [comment]
can you send me the input you've used?

**Comment by Rojas-Binny** [comment]
I have attached the image with user details that I have added

**Comment by Samyukta-b** [comment]
!bounty 300

**Comment by bwaklog** [comment]
!bounty 300

**Comment by DedLad** [comment]
!bounty 50

**Pull request merged**
